In [1]:
import numpy as np

# Reinforcement Learning #2

## Markov Decision Process

**Markov Decision Process** (MDP) is a system consisting of three types of entities: states, actions and rewards. Going from state $s_1$ to another state $s'$, we need to pick an action that can lead us to $s'$. Each action has a transition probability $T$. 

For instance, we can find ourselves in a state $s_1$ with possible actions $a_0$ and $a_1$. Action $a_0$ might have transition probability of 1 that leads us back to  $s_1$ and transition probability of 0 that leads us to $s_2$. On the other hand, $a_1$ can have probability $0.1$ that we'll go back to $s_1$ and probability $0.9$ that we pass to $s_2$.

Additionaly, transitions may return rewards. For instance, trandition from $s_1$ to itself via $a_0$ may return a reward of +50, while other transitions may return rewards of zero. In certain circumstances, in such a world it would be easy to stuck in $s_1$ and never explore the world.

## Q-Value Iteration Algorithm

**Q-Value Iteration Algorithm** lets us find the optimal strategy for a given MDP and a given set of parameters.

It's defined by the following formula:

$$\large Q_{k+1}(s, a) = \sum_{s'} T(s, a, s')[R(s, a, s') + \gamma \cdot \max_{a'} Q_k(s', a')]$$

for all $(s', a)$

where:

* $T(s, a, s')$ is the transition probability between $s$ and $s'$ when choosing $a$
* $R(s, a, s')$ is the reward returned by this transition
* $\gamma$ is the discount factor.

<br>

Let's define an MDP with three states and a couple of possible actions!

In [26]:
# Define an MDP
transition_probas = [ # shape => (s, a, s')
    [[.7, .3, 0.], [1., 0., 0.], [.8, .2, 0.]],
    [[0., 1., 0.], None, [0., 0., 1.]],
    [None, [.8, .1, .1], None]
]

rewards = [ # shape => (s, a, s')
    [[+10, 0, 0], [0, 0, 0], [0, 0, 0]],
    [[0, 0, 0], [0, 0, 0], [0, 0, -50]],
    [[0, 0, 0], [+40, 0, 0], [0, 0, 0]]
]

possible_actions = [[0, 1, 2], [0, 2], [1]]

In [27]:
# Initialize Q-Values
Q_vals = np.full((3, 3), -np.inf)  # -> -inf stands for impossible actions

# Iterate and fill in possible actions with zeros
for state, actions in enumerate(possible_actions):
    Q_vals[state, actions] = 0.

In [28]:
# Sanity check
Q_vals

array([[  0.,   0.,   0.],
       [  0., -inf,   0.],
       [-inf,   0., -inf]])

In [29]:
# Define the params
gamma = .9
N_ITER = 50

In [30]:
# Apply the algo

def update_Q(gamma, n_iters):
    
    for i in range(n_iters):

        if i % 10 == 0:
            print(f'Iteration {i}')

        Q_prev = Q_vals.copy()   # Always have a fresh copy of the previous step before updates
        for s in range(len(possible_actions)):    # Iterate over n of states 
            for a in possible_actions[s]:
                Q_vals[s, a] = np.sum([
                    transition_probas[s][a][s_p] * (rewards[s][a][s_p] + gamma * np.max(Q_prev[s_p]))
                    for s_p in range(len(possible_actions))
                ])
            

In [32]:
update_Q(.9, N_ITER)

Iteration 0
Iteration 10
Iteration 20
Iteration 30
Iteration 40


In [33]:
Q_vals

array([[18.91891892, 17.02702702, 13.62162162],
       [ 0.        ,        -inf, -4.87971488],
       [       -inf, 50.13365013,        -inf]])

In [34]:
# Try higher gamma
Q_vals = np.full((3, 3), -np.inf)  # -> -inf stands for impossible actions

# Iterate and fill in possible actions with zeros
for state, actions in enumerate(possible_actions):
    Q_vals[state, actions] = 0.

In [35]:
update_Q(.95, N_ITER)

Iteration 0
Iteration 10
Iteration 20
Iteration 30
Iteration 40


In [36]:
Q_vals

array([[21.73304188, 20.63807938, 16.70138772],
       [ 0.95462106,        -inf,  1.01361207],
       [       -inf, 53.70728682,        -inf]])